### ISSUE TITLE
cargo test fail:  Not Found, url: https://huggingface.co/datasets/wikitext/resolve/refs%2Fconvert%2Fparquet/wikitext-103-v1/wikitext-test.parquet

### ISSUE THREAD

**Issue by evgenyigumnov** [huggingface/hf-hub#17]
main branch after git pull

PS C:\Users\igumn\hf-hub> cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.10s
     Running unittests src\lib.rs (target\debug\deps\hf_hub-082cd1143db02bea.exe)

running 5 tests
test tests::token_path ... ok
test api::sync::tests::dataset ... FAILED
test api::sync::tests::info ... FAILED
test api::sync::tests::detailed_info ... ok
test api::sync::tests::simple ... ok

failures:

---- api::sync::tests::dataset stdout ----
thread 'api::sync::tests::dataset' panicked at 'called `Result::unwrap()` on an `Err` value: RequestError(Status(404, Response[status: 404, status_text: Not Found, url: https://huggingface.co/datasets/wikitext/resolve/refs%2Fconvert%2Fparquet/wikitext-103-v1/wikitext-test.parquet]))', src\api\sync.rs:583:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- api::sync::tests::info stdout ----
thread 'api::sync::tests::info' panicked at 'assertion failed: `(left == right)`
  left: `RepoInfo { siblings: [Siblings { rfilename: ".gitattributes" }, Siblings { rfilename: "wikitext-103-raw-v1/test/0000.parquet" }, Siblings { rfilename: "wikitext-103-raw-v1/train/0000.parquet" }, Siblings { rfilename: "wikitext-103-raw-v1/train/0001.parquet" }, Siblings { rfilename: "wikitext-103-raw-v1/validation/0000.parquet" }, Siblings { rfilename: "wikitext-103-v1/test/0000.parquet" }, Siblings { rfilename: "wikitext-103-v1/test/index.duckdb" }, Siblings { rfilename: "wikitext-103-v1/train/0000.parquet" }, Siblings { rfilename: "wikitext-103-v1/train/0001.parquet" }, Siblings { rfilename: "wikitext-103-v1/validation/0000.parquet" }, Siblings { rfilename: "wikitext-103-v1/validation/index.duckdb" }, Siblings { rfilename: "wikitext-2-raw-v1/test/0000.parquet" }, Siblings { rfilename: "wikitext-2-raw-v1/test/index.duckdb" }, Siblings { rfilename: "wikitext-2-raw-v1/train/0000.parquet" }, Siblings { rfilename: "wikitext-2-raw-v1/train/index.duckdb" }, Siblings { rfilename: "wikitext-2-raw-v1/validation/0000.parquet" }, Siblings { rfilename: "wikitext-2-raw-v1/validation/index.duckdb" }, Siblings { rfilename: "wikitext-2-v1/test/0000.parquet" }, Siblings { rfilename: "wikitext-2-v1/train/0000.parquet" }, Siblings { rfilename: "wikitext-2-v1/validation/0000.parquet" }], sha: "29104e21c58d6f33e93ee0d78dbf7141b40fe46c" }`,
 right: `RepoInfo { siblings: [Siblings { rfilename: ".gitattributes" }, Siblings { rfilename: "wikitext-103-raw-v1/wikitext-test.parquet" }, Siblings { rfilename: "wikitext-103-raw-v1/wikitext-train-00000-of-00002.parquet" }, Siblings { rfilename: "wikitext-103-raw-v1/wikitext-train-00001-of-00002.parquet" }, Siblings { rfilename: "wikitext-103-raw-v1/wikitext-validation.parquet" }, Siblings { rfilename: "wikitext-103-v1/test/index.duckdb" }, Siblings { rfilename: "wikitext-103-v1/validation/index.duckdb" }, Siblings { rfilename: "wikitext-103-v1/wikitext-test.parquet" }, Siblings { rfilename: "wikitext-103-v1/wikitext-train-00000-of-00002.parquet" }, Siblings { rfilename: "wikitext-103-v1/wikitext-train-00001-of-00002.parquet" }, Siblings { rfilename: "wikitext-103-v1/wikitext-validation.parquet" }, Siblings { rfilename: "wikitext-2-raw-v1/test/index.duckdb" }, Siblings { rfilename: "wikitext-2-raw-v1/train/index.duckdb" }, Siblings { rfilename: "wikitext-2-raw-v1/validation/index.duckdb" }, Siblings { rfilename: "wikitext-2-raw-v1/wikitext-test.parquet" }, Siblings { rfilename: "wikitext-2-raw-v1/wikitext-train.parquet" }, Siblings { rfilename: "wikitext-2-raw-v1/wikitext-validation.parquet" }, Siblings { rfilename: "wikitext-2-v1/wikitext-test.parquet" }, Siblings { rfilename: "wikitext-2-v1/wikitext-train.parquet" }, Siblings { rfilename: "wikitext-2-v1/wikitext-validation.parquet" }], sha: "06ac3f4b846ef171cae5a48a35c3e85f2b44f636" }`', src\api\sync.rs:606:9

failures:
    api::sync::tests::dataset
    api::sync::tests::info

test result: FAILED. 3 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.95s

error: test failed, to rerun pass `--lib`

**Comment by Narsil** [comment]
Are you really on `main`?

**Comment by Narsil** [comment]
This fixed it : https://github.com/huggingface/hf-hub/pull/16
