### ISSUE TITLE
Support incremental downloads of large files somehow.

### ISSUE THREAD

**Issue by crlf0710** [huggingface/hf-hub#18]
For larger models (maybe >= 3.0 GB), there's a larger chance that the downloads get aborted by network failures with slower networks. I wonder if it's possible to make the downloads incremental, so restart from the beginning is not needed?

**Comment by benedikt-schaber** [comment]
@crlf0710  If you have not already begun working on this and would not mind, I should be able to create a PR this weekend to introduce the same retry capabilities to sync that the tokio version already has.

@Narsil Regarding resumable downloads, could we create our own version of .incomplete (perhaps in the tmp folder)? Using etag for identification and creating two files for each download, the partial file itself and a meta file containing the chunk size and the successfully downloaded chunks (as a 'checklist' to keep it async). We could then also assume that all successfully downloaded chunks are correct and just add the missing chunks.
We could rechunk the contiguous chunk sequences or require users to reuse the same chunk size.
Does this sound somewhat reasonable/Would such a feature be welcomed? I could then also write the PR for this.

**Comment by Narsil** [comment]
Done in : https://github.com/huggingface/hf-hub/pull/84
