### ISSUE TITLE
HTTP_PROXY Environment Variable is not working

### ISSUE THREAD

**Issue by mqyang56** [huggingface/hf-hub#28]
As the title

**Comment by Narsil** [comment]
Not going to be implemented here.

**Comment by aohan237** [comment]
@Narsil 

in the latest ureq, an added feature gate for env proxy support

`ureq = { version = "2.8.0", optional = true, features = ["native-tls", "json", "socks-proxy"] }`

to

`ureq = { version = "2.9.1", optional = true, features = ["native-tls", "json", "socks-proxy","proxy-from-env"] }`

should work
