### ISSUE TITLE
Wrong URL for downloading models

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/hf-hub#43]
According to @ivanbaldo, the URL is badly formed when attempting to retrieve the tokenizer. Here is the error:

`Error: APIError { data: "request error: https://huggingface.co/meta-llama/Llama-27b-chat-hf/resolve/main/tokenizer.json: status code 404" }`

And the original issue. EricLBuehler/candle-vllm#29 where I have linked in my comment the code which calls `hf_hub`.

Is this a problem with my implementation?

**Comment by pcuenca** [comment]
I think these lines are wrong: https://github.com/EricLBuehler/candle-vllm/blob/9e7d08023db0214c5c5586b1df980378a68f8bdb/src/lib.rs#L47. The model id is `meta-llama/Llama-2-7b-chat-hf`, not `meta-llama/Llama-27b-chat-hf`.

**Comment by EricLBuehler** [comment]
Thank you!
