### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by swfsql** [huggingface/hf-hub#45]
Hello, it would be nice if there was a wasm support on the library (or a wasm port of it).

I'm aware that many dependencies would not be compatible, nor the workflow itself (creating directories, indicating progress, etc). Also, I can't say there would be a lot of demand for this feature (I myself just want to experiment with some wasm).

For one thing, there are a few options for storage cache for a wasm app: 
- [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) could work well, with [indexed_db_futures](https://crates.io/crates/indexed_db_futures) being an option.
- [Cache](https://developer.mozilla.org/en-US/docs/Web/API/Cache) storage is being used by the candle wasm examples, which could also work, but being limited to request-responses I think would be a different design from how hf-hub behaves.
- [Origin private fs](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system) could be the most relatable option, but I don't think there are good rust wrapping libraries for this.

I've started a [drafty wasm port](https://github.com/swfsql/hf-hub/tree/wasm), and if it works reasonably well I'll attach a PR.
Thanks!

**Comment by Narsil** [comment]
Nice. 

I'm going to close this, since it's pretty old.

However nice job doing this in WASM. As you said, I don't think it's a great fit for this crate since both network and filesystem are significantly differrent in browser-wasm (Which is what I'm assuming most wasm users are targetting).

**Comment by tuananh** [comment]
@Narsil hi, what about wasi support?

**Comment by swfsql** [comment]
@tuananh if you see no problem in using a old versioned and opinionated trial at combining was and hf-hub, you can use the draft that I mentioned. As of today, it is working well as per [this project](https://github.com/swfsql/mamba-minimal-dfdx-example)/[online example](https://swfsql.github.io/mamba-minimal-dfdx-example/) - alternatively, [project](https://github.com/swfsql/burn-mamba-example)/[online](https://swfsql.github.io/burn-mamba-example/).

**Comment by tuananh** [comment]
thanks. i need wasm support as well.
