### ISSUE TITLE
Add support for `native-tls`

### ISSUE THREAD

**Issue by McPatate** [huggingface/hf-hub#56]
It appears that adding `native-tls` as a feature in `ureq` is not sufficient, and that the `native_tls::TlsConnector` must explicitly be used in code.

**Comment by jamiegl** [comment]
I've implemented something using [rustls-native-certs](https://crates.io/crates/rustls-native-certs) to get around some problems I was having with candle using our internal certificates. It shouldn't be too hard to add here if we're interested in that approach.

**Comment by Narsil** [comment]
Option shown here: https://github.com/huggingface/hf-hub?tab=readme-ov-file#ssltls
