### ISSUE TITLE
Calling for a new version released with feature `rustls-tls`

### ISSUE THREAD

**Issue by TD-Sky** [huggingface/hf-hub#73]
`hf-hub` is used widely in rust AI develop ecosystem so many dependents introduce openssl, which makes cross compilation failure-prone. I often avoid the cross compilation problems via statically link rustls (statically link openssl only work sometime).

I wish you could release a new version to give users the freedom of choosing TLS, please.

**Comment by sssemil** [comment]
Yes, please.

**Comment by sssemil** [comment]
I published a fork here for my needs - https://crates.io/crates/hf-hub-enfer, hope it helps.

**Comment by Narsil** [comment]
This is done on master, release of `0.4.0` should happen soon.

You can choose any cross product with `["ureq", "reqwest"] X [ "native-tls", "rustls-tls"]`.

**Comment by Narsil** [comment]
Option shown here :https://github.com/huggingface/hf-hub?tab=readme-ov-file#ssltls
