### ISSUE TITLE
Url construction with revision looks erroneous

### ISSUE THREAD

**Issue by jorgeantonio21** [huggingface/hf-hub#76]
In the current implementation:

https://github.com/huggingface/hf-hub/blob/main/src/api/sync.rs#L127

the value `/resolve/` is hardcoded in the url path. This seems to be incorrectly specified, as some models, require `/blob/`instead, such as:

1. https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct/blob/main/model.safetensors.index.json
2. https://huggingface.co/intfloat/multilingual-e5-large-instruct/blob/main/model.safetensors

**Comment by Narsil** [comment]
`resolve` is the correct URL.

`blob` also exists and might be refered, but it's the browsable version, not the raw file.
